;Additional Symbols.ahk Version 0.0.6. Copyright © ivaniesta14, 2018-2021. Distributed under CC-BY 4.0

/*

Hotstrings in this file have a prefix section, a character section and some have also a variant section.

The prefix is a short description of the block the character belongs to, followed by an underscore unless the character is
a member of an alphabet (eg. greek, cyrillic or latin alphabets) or is a fraction. Katakana's prefix is "kata".

The (optional) variant section differentiates the character variants (diacritics, left and right brackets...) and is
always preceded by an underscore.
If a character has multiple diacritics, they are separated by underscores and listed from the center towards the outside.
If a character has a diacritic and another modification (reversed, closed...), the modification goes first and then the
diacritic.
(Some hotstrings do not follow this structure, especially if the character is similar to another one that has a hotstring)
(In some cases, the variant section goes before the character section (eg. ‗ "punc_double_underscore"))

Arrows and brackets have their direction (left, right, up, down...) at the end of the variant section.
Arrow modifiers are ordered in this order: head variations, tail variations, middle variations.

Examples:

ǖ ⇒	latu_diaeresis_macron
	---=~~~~~~~~~~~~~~~~~
- Latin alphabet → no underscore
= Letter u
~ Diacritics: diaeresis and macron from center to outside

ͽ ⇒	gresigma_lunate_dot_reversed
	---=====~~~~~~~~~~~~~~~~~~~~
- Greek alphabet → no underscore
= Letter sigma
~ Variations: lunate, dotted, reversed (diacritic and modifications, but ͼ "gresigma_lunate_dot" exists)

⤘ ⇒	arrow_twohead_tail_doublestroke_right
	------~~~~~~~~~~~~~~~~~~~~~~~~~~=====
- Arrow → underscore
= Pointing towards right
~ Arrow has two heads, two strokes and a tail → twohead_tail_doublestroke

It is possible for some characters to be displayed as a rectangle in some fonts.
Make sure to use an Unicode-compatible font when browsing this script.
Certain characters are too wide to be square in some monospace fonts, which may cause weird column alignments.

*/

#NoEnv   ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn   ; Enable warnings to assist with detecting common errors.
SendMode Input   ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%   ; Ensures a consistent starting directory.

#SingleInstance force ;Reload and replace current script when opening file instead of adding another instance.
#Hotstring O ;Hotstrings will consume the character that triggered it (eg. typing "gra " will not have the space after α).

;################################################                    GREEK, COPTIC AND EXTENSIONS
::greek_alpha::α ;Greek and Coptic
::greek_beta::β
::greek_gamma::γ
::greek_delta::δ
::greek_epsilon::ε
::greek_zeta::ζ
::greek_eta::η
::greek_theta::θ
::greek_iota::ι
::greek_kappa::κ
::greek_lambda::λ
::greek_mu::μ
::greek_nu::ν
::greek_xi::ξ
::greek_omicron::ο
::greek_pi::π
::greek_rho::ρ
::greek_sigma_final::ς
::greek_sigma::σ
::greek_tau::τ
::greek_upsilon::υ
::greek_phi::φ
::greek_chi::χ
::greek_psi::ψ
::greek_omega::ω

::gra::α
::grb::β
::grg::γ
::grd::δ
::gre::ε
::grz::ζ
::grh::η
::gru::θ
::gri::ι
::grk::κ
::grl::λ
::grm::μ
::grn::ν
::grj::ξ
::gro::ο
::grp::π
::grr::ρ
::grw::ς
::grs::σ
::grt::τ
::gry::υ
::grf::φ
::grx::χ
::grc::ψ
::grv::ω

::grealpha::α
::grebeta::β
::gregamma::γ
::gredelta::δ
::greepsilon::ε
::grezeta::ζ
::greeta::η
::gretheta::θ
::greiota::ι
::grekappa::κ
::grelambda::λ
::gremu::μ
::grenu::ν
::grexi::ξ
::greomicron::ο
::grepi::π
::grerho::ρ
::gresigma_final::ς
::gresigma::σ
::gretau::τ
::greupsilon::υ
::grephi::φ
::grechi::χ
::grepsi::ψ
::greomega::ω

::greheta::ͱ
::gresampi_archaic::ͳ
::grenumeral::ʹ
::grenumeral_low::͵
::gredigamma_pamphylian::ͷ
::greypogegrammeni::ͺ
::gresigma_lunate_reversed::ͻ
::gresigma_lunate_dot::ͼ
::gresigma_lunate_dot_reversed::ͽ
::grequestionmark::;
::gretonos::΄
::gredialytikatonos::΅
::greanoteleia::·

::grealpha_tonos::ά
::greepsilon_tonos::έ
::greeta_tonos::ή
::greiota_tonos::ί
::greupsilon_dialytika_tonos::ΰ
::greiota_dialytika_tonos::ΐ

::greiota_dialytika::ϊ
::greupsilon_dialytika::ϋ
::greomicron_tonos::ό
::greupsilon_tonos::ύ
::greomega_tonos::ώ
::grebeta_cursive::ϐ
::gretheta_cursive::ϑ
::greupsilon_hook::ϒ
::greupsilon_hook_acute::ϓ
::greupsilon_hook_diaeresis::ϔ
::grephi_cursive::ϕ
::grepi_cursive::ϖ
::grekai::ϗ
::grekoppa_archaic::ϙ
::grestigma::ϛ
::gredigmamma::ϝ
::grekoppa::ϟ
::gresampi::ϡ

::copshei::ϣ
::copfei::ϥ
::copkhei::ϧ
::copkori::ϩ
::copgangia::ϫ
::copshima::ϭ
::copdei::ϯ
::grekappa_cursive::ϰ
::grerho_cursive::ϱ
::gresigma_lunate::ϲ
::greyot::ϳ
::greepsilon_lunate::ϵ
::greepsilon_lunate_reversed::϶
::gresho::ϸ
::gresan::ϻ
::grerho_stroke::ϼ

::grealpha_psili::ἀ ;Greek Extended
::grealpha_dasia::ἁ
::grealpha_psili_varia::ἂ
::grealpha_dasia_varia::ἃ
::grealpha_psili_oxia::ἄ
::grealpha_dasia_oxia::ἅ
::grealpha_psili_perispomeni::ἆ
::grealpha_dasia_perispomeni::ἇ
::greepsilon_psili::ἐ
::greepsilon_dasia::ἑ
::greepsilon_psili_varia::ἒ
::greepsilon_dasia_varia::ἓ
::greepsilon_psili_oxia::ἔ
::greepsilon_dasia_oxia::ἕ
::greeta_psili::ἠ
::greeta_dasia::ἡ
::greeta_psili_varia::ἢ
::greeta_dasia_varia::ἣ
::greeta_psili_oxia::ἤ
::greeta_dasia_oxia::ἥ
::greeta_psili_perispomeni::ἦ
::greeta_dasia_perispomeni::ἧ
::greiota_psili::ἰ
::greiota_dasia::ἱ
::greiota_psili_varia::ἲ
::greiota_dasia_varia::ἳ
::greiota_psili_oxia::ἴ
::greiota_dasia_oxia::ἵ
::greiota_psili_perispomeni::ἶ
::greiota_dasia_perispomeni::ἷ
::greomicron_psili::ὀ
::greomicron_dasia::ὁ
::greomicron_psili_varia::ὂ
::greomicron_dasia_varia::ὃ
::greomicron_psili_oxia::ὄ
::greomicron_dasia_oxia::ὅ
::greupsilon_psili::ὐ
::greupsilon_dasia::ὑ
::greupsilon_psili_varia::ὒ
::greupsilon_dasia_varia::ὓ
::greupsilon_psili_oxia::ὔ
::greupsilon_dasia_oxia::ὕ
::greupsilon_psili_perispomeni::ὖ
::greupsilon_dasia_perispomeni::ὗ
::greomega_psili::ὠ
::greomega_dasia::ὡ
::greomega_psili_varia::ὢ
::greomega_dasia_varia::ὣ
::greomega_psili_oxia::ὤ
::greomega_dasia_oxia::ὥ
::greomega_psili_perispomeni::ὦ
::greomega_dasia_perispomeni::ὧ

::grealpha_varia::ὰ
::grealpha_oxia::ά
::greepsilon_varia::ὲ
::greepsilon_oxia::έ
::greeta_varia::ὴ
::greeta_oxia::ή
::greiota_varia::ὶ
::greiota_oxia::ί
::greomicron_varia::ὸ
::greomicron_oxia::ό
::greupsilon_varia::ὺ
::greupsilon_oxia::ύ
::greomega_varia::ὼ
::greomega_oxia::ώ

::grealpha_psili_ypogegrammeni::ᾀ
::grealpha_dasia_ypogegrammeni::ᾁ
::grealpha_psili_varia_ypogegrammeni::ᾂ
::grealpha_dasia_varia_ypogegrammeni::ᾃ
::grealpha_psili_oxia_ypogegrammeni::ᾄ
::grealpha_dasia_oxia_ypogegrammeni::ᾅ
::grealpha_psili_perispomeni_ypogegrammeni::ᾆ
::grealpha_dasia_perispomeni_ypogegrammeni::ᾇ
::grealpha_psili_ypogegrammeni::ᾐ
::grealpha_dasia_ypogegrammeni::ᾑ
::grealpha_psili_varia_ypogegrammeni::ᾒ
::grealpha_dasia_varia_ypogegrammeni::ᾓ
::grealpha_psili_oxia_ypogegrammeni::ᾔ
::grealpha_dasia_oxia_ypogegrammeni::ᾕ
::grealpha_psili_perispomeni_ypogegrammeni::ᾖ
::grealpha_dasia_perispomeni_ypogegrammeni::ᾗ
::grealpha_psili_ypogegrammeni::ᾠ
::grealpha_dasia_ypogegrammeni::ᾡ
::grealpha_psili_varia_ypogegrammeni::ᾢ
::grealpha_dasia_varia_ypogegrammeni::ᾣ
::grealpha_psili_oxia_ypogegrammeni::ᾤ
::grealpha_dasia_oxia_ypogegrammeni::ᾥ
::grealpha_psili_perispomeni_ypogegrammeni::ᾦ
::grealpha_dasia_perispomeni_ypogegrammeni::ᾧ

::grealpha_vrachy::ᾰ
::grealpha_macron::ᾱ
::grealpha_varia_ypogegrammeni::ᾲ
::grealpha_ypogegrammeni::ᾳ
::grealpha_oxia_ypogegrammeni::ᾴ
::grealpha_perispomeni::ᾶ
::grealpha_perispomeni_ypogegrammeni::ᾷ
::greeta_varia_ypogegrammeni::ῂ
::greeta_ypogegrammeni::ῃ
::greeta_oxia_ypogegrammeni::ῄ
::greeta_perispomeni::ῆ
::greeta_perispomeni_ypogegrammeni::ῇ
::greiota_vrachy::ῐ
::greiota_macron::ῑ
::greiota_dialytika_varia::ῒ
::greiota_dialytika_oxia::ΐ
::greiota_perispomeni::ῖ
::greiota_perispomeni_ypogegrammeni::ῗ
::greupsilon_vrachy::ῠ
::greupsilon_macron::ῡ
::greupsilon_dialytika_varia::ῢ
::greupsilon_dialytika_oxia::ΰ
::grerho_psili::ῤ
::grerho_dasia::ῥ
::greupsilon_perispomeni::ῦ
::greupsilon_perispomeni_ypogegrammeni::ῧ
::greomega_varia_ypogegrammeni::ῲ
::greomega_ypogegrammeni::ῳ
::greomega_oxia_ypogegrammeni::ῴ
::greomega_perispomeni::ῶ
::greomega_perispomeni_ypogegrammeni::ῷ

;################################################                    MATHEMATICAL SYMBOLS
::math_forall::∀ ;Mathematical Operators
::math_partial::∂
::math_exists::∃
::math_exists_not::∄
::math_emptyset::∅
::math_delta::∆
::math_nabla::∇
::math_elementof::∈
::math_elementof_not::∉
::math_contains::∋
::math_contains_not::∌
::math_endofproof::∎
::math_product::∏
::math_coproduct::∐
::math_sum::∑
::math_minusplus::∓
::math_setdiff::∖
::math_asterisk::∗
::math_ring::∘
::math_bullet::∙
::math_sqrt::√
::math_cbrt::∛
::math_fourthroot::∜
::math_propto::∝
::math_inf::∞
::math_rightangle::∟
::math_angle::∠
::math_divides::∣
::math_divides_not::∤
::math_parallel::∥
::math_parallel_not::∦
::math_and::∧
::math_or::∨
::math_intersect::∩
::math_union::∪
::math_int::∫
::math_int_double::∬
::math_int_triple::∭
::math_int_contour::∮
::math_int_surface::∯
::math_int_volume::∰
::math_therefore::∴
::math_because::∵
::math_ratio::∶
::math_proportion::∷
::math_minus_dot::∸
::math_excess::∹
::math_proportion_geometric::∺
::math_homothetic::∻
::math_tilde::∼
::math_tilde_reversed::∽
::math_wreathproduct::≀
::math_tilde_not::≁
::math_tilde_minus::≂
::math_equals_asymptote::≃
::math_equals_asymptote_not::≄
::math_equals_approximate::≅
::math_equals_approximate_notequal::≆
::math_equals_approximate_not::≇
::math_equals_almost::≈
::math_equals_almost_not::≉
::math_equals_almost_equal::≊
::math_tilde_tilde::≋
::math_equals_all::≌
::math_equivalent::≍
::math_equivalent_geometric::≎
::math_differencebetween::≏
::math_equals_dot::≐
::math_equals_geometric::≑
::math_equals_approx_image::≒
::math_equals_image_approx::≓
::math_equals_colon::≔
::math_equals_colon_reversed::≕
::math_equals_middlering::≖
::math_equals_ring::≗
::math_equals_correspondence::≘
::math_equals_estimate::≙
::math_equals_equiangular::≚
::math_equals_star::≛
::math_equals_delta::≜
::math_equals_definition::≝
::math_equals_measurement::≞
::math_equals_question::≟
::math_equals_not::≠
::math_identical::≡
::math_identical_not::≢
::math_equivalent_strict::≣
::math_leq::≤
::math_geq::≥
::math_lt_eq::≦
::math_gt_eq::≧
::math_lt_eq_not::≨
::math_gt_eq_not::≩
::math_between::≬
::math_equivalent_not::≭
::math_lt_lt::≪
::math_gt_gt::≫
::math_lt_not::≮
::math_gt_not::≯
::math_leq_not::≰
::math_geq_not::≱
::math_lt_equiv::≲
::math_gt_equiv::≳
::math_lt_equiv_not::≴
::math_gt_equiv_not::≵
::math_lt_gt::≶
::math_gt_lt::≷
::math_lt_gt_not::≸
::math_gt_lt_not::≹
::math_precedes::≺
::math_succeeds::≻
::math_precedes_eq::≼
::math_succeeds_eq::≽
::math_precedes_equiv::≾
::math_succeeds_equiv::≿
::math_precedes_not::⊀
::math_succeeds_not::⊁
::math_subset::⊂
::math_superset::⊃
::math_subset_not::⊄
::math_superset_not::⊅
::math_subset_eq::⊆
::math_superset_eq::⊇
::math_subset_eq_not::⊈
::math_superset_eq_not::⊉
::math_subset_noteq::⊊
::math_superset_noteq::⊋
::math_multiset::⊌
::math_multiset_times::⊍
::math_multiset_plus::⊎
::math_squareimage::⊏
::math_squareoriginal::⊐
::math_squareimage_eq::⊑
::math_squareoriginal_eq::⊒
::math_squarecap::⊓
::math_squarecup::⊔
::math_circleplus::⊕
::math_circleminus::⊖
::math_circletimes::⊗
::math_circleslash::⊘
::math_circledot::⊙
::math_circlering::⊚
::math_circlestar::⊛
::math_circlequals::⊜
::math_circledash::⊝
::math_squareplus::⊞
::math_squareminus::⊟
::math_squaretimes::⊠
::math_squaredot::⊡
::math_rtack::⊢
::math_ltack::⊣
::math_dtack::⊤
::math_utack::⊥
::math_assertion::⊦
::math_models::⊧
::math_true::⊨
::math_forces::⊩
::math_turnstile_three_one::⊪
::math_turnstile_two_two::⊫
::math_proves_not::⊬
::math_true_not::⊭
::math_forces_not::⊮
::math_turnstile_two_two_not::⊯
::math_precedes_relation::⊰
::math_succeeds_relation::⊱
::math_normalsubgroup::⊲
::math_containsnormalsubgroup::⊳
::math_normalsubgroup_eq::⊴
::math_containsnormalsubgroup_eq::⊵
::math_originalof::⊶
::math_imageof::⊷
::math_multimap::⊸
::math_xor::⊻
::math_nand::⊼
::math_nor::⊽
::math_rightangle_arc::⊾
::math_righttriangle::⊿
::math_diamond::⋄
::math_dot::⋅
::math_star::⋆
::math_divisiontimes::⋇
::math_bowtie::⋈
::math_semidirectproduct_normal_left::⋉
::math_semidirectproduct_normal_right::⋊
::math_semidirectproduct_left::⋋
::math_semidirectproduct_right::⋌
::math_equals_tilde_reversed::⋍
::math_or_curly::⋎
::math_and_curly::⋏
::math_subset_double::⋐
::math_superset_double::⋑
::math_intersection_double::⋒
::math_union_double::⋓
::math_equal_parallel::⋕
::math_lt_dot::⋖
::math_gt_dot::⋗
::math_trilt::⋘
::math_trigt::⋙
::math_lt_eq_gt::⋚
::math_gt_eq_lt::⋛
::math_equals_lt::⋜
::math_equals_gt::⋝
::math_equals_precedes::⋞
::math_equals_succeeds::⋟
::math_precedes_eq_not::⋠
::math_succeeds_eq_not::⋡
::math_squareimage_eq_not::⋢
::math_squareoriginal_eq_not::⋣
::math_squareimage_noteq::⋤
::math_squareoriginal_noteq::⋥
::math_lt_notequiv::⋦
::math_gt_notequiv::⋧
::math_precedes_notequiv::⋨
::math_succeeds_notequiv::⋩
::math_normalsubgroup_not::⋪
::math_containsnormalsubgroup_not::⋫
::math_normalsubgroup_eq_not::⋬
::math_containsnormalsubgroup_eq_not::⋭
::math_verticalellipsis::⋮
::math_horizontalellipsis::⋯
::math_uprightellipsis::⋰
::math_downrightellipsis::⋱
::math_elementof_horizontalstroke::⋲
::math_elementof_verticalbar::⋳
::math_elementof_verticalbar_small::⋴
::math_elementof_dot::⋵
::math_elementof_overbar::⋶
::math_elementof_overbar_small::⋷
::math_elementof_underbar::⋸
::math_elementof_twobars::⋹
::math_contains_horizontalstroke::⋺
::math_contains_verticalbar::⋻
::math_contains_verticalbar_small::⋼
::math_contains_overbar::⋽
::math_contains_overbar_small::⋾
::math_bagmember::⋿

::math_nary_circledot::⨀ ;Supplemental Mathematical Operators
::math_nary_circleplus::⨁
::math_nary_circletimes::⨂
::math_nary_uniondot::⨃
::math_nary_unionplus::⨄
::math_nary_squareintersection::⨅
::math_nary_squareunion::⨆
::math_and_and_big::⨇
::math_or_or_big::⨈
::math_nary_times::⨉
::math_sum_modulotwo::⨊
::math_sum_integral::⨋
::math_int_quad::⨌
::math_int_stroke::⨍
::math_int_doublestroke::⨎
::math_int_slash::⨏
::math_int_circulation::⨐
::math_int_anticlockwise::⨑
::math_int_rectanglearoundpole::⨒
::math_int_semicirclearoundpole::⨓
::math_int_linewithoutpole::⨔
::math_int_aroundpoint::⨕
::math_int_quaternion::⨖
::math_int_leftarrowhook::⨗
::math_int_times::⨘
::math_int_intersection::⨙
::math_int_union::⨚
::math_int_overbar::⨛
::math_int_underbar::⨜
::math_join::⨝
::math_lefttriangle::⨞
::math_znotation_schemacomposition::⨟
::math_znotation_schemapiping::⨠
::math_znotation_schemaprojection::⨡
::math_plus_ring::⨢
::math_plus_circumflex::⨣
::math_plus_tilde::⨤
::math_plus_dotbelow::⨥
::math_plus_tildebelow::⨦
::math_plus_subtwo::⨧
::math_plus_triangle::⨨
::math_minus_comma::⨩
::math_minus_dotbelow::⨪
::math_minus_fallingdots::⨫
::math_minus_raisingdots::⨬
::math_plus_lefthalfcircle::⨭
::math_plus_righthalfcircle::⨮
::math_crossproduct::⨯
::math_times_dot::⨰
::math_times_underbar::⨱
::math_semidirectproduct_bottom::⨲
::math_smashproduct::⨳
::math_times_lefthalfcircle::⨴
::math_times_righthalfcircle::⨵
::math_circletimes_circumflex::⨶
::math_circletimes_circle::⨷
::math_circledivision::⨸
::math_triangleplus::⨹
::math_triangleminus::⨺
::math_triangletimes::⨻
::math_interiorproduct::⨼
::math_interiorproduct_right::⨽
::math_znotation_relationalcomposition::⨾
::math_coproduct::⨿
::math_intersection_dot::⩀
::math_union_minus::⩁
::math_union_overbar::⩂
::math_intersection_overbar::⩃
::math_intersection_and::⩄
::math_union_or::⩅
::math_intersection_union::⩆
::math_union_intersection::⩇
::math_intersection_bar_union::⩈
::math_union_bar_intersection::⩉
::math_union_joined::⩊
::math_intersection_joined::⩋
::math_union_closed::⩌
::math_intersection_closed::⩍
::math_intersection_square_double::⩎
::math_union_square_double::⩏
::math_union_closed_smashproduct::⩐
::math_and_dot::⩑
::math_or_dot::⩒
::math_and_double::⩓
::math_or_double::⩔
::math_and_intersecting::⩕
::math_or_intersecting::⩖
::math_or_sloping::⩗
::math_and_sloping::⩘
::math_and_or::⩙
::math_and_middlestem::⩚
::math_or_middlestem::⩛
::math_and_horizontalstroke::⩜
::math_or_horizontalstroke::⩝
::math_and_doubleoverbar::⩞
::math_and_underbar::⩟
::math_and_doubleunderbar::⩠
::math_vee_underbar::⩡
::math_or_doubleoverbar::⩢
::math_or_doubleunderbar::⩣
::math_znotation_domainantirestriction::⩤
::math_znotation_rangeantiresrtiction::⩥
::math_equals_dotbelow::⩦
::math_identical_dotabove::⩧
::math_triplehorizontal_doublevertical::⩨
::math_triplehorizontal_triplevertical::⩩
::math_tilde_dotabove::⩪
::math_tilde_risingdots::⩫
::math_tilde_minus_tilde::⩬
::math_equals_congruent_dotabove::⩭
::math_equals_asterisk::⩮
::math_equals_almost_circumflex::⩯
::math_equals_almost_equals::⩰
::math_equals_plus::⩱
::math_plus_equals::⩲
::math_equals_tilde::⩳
::math_equals_doublecolon::⩴
::math_equals_equals::⩵
::math_equals_equals_equals::⩶
::math_equals_twodotsabove_twodotsbelow::⩷
::math_equivalent_fourdotsabove::⩸
::math_lt_circle::⩹
::math_gt_circle::⩺
::math_lt_question::⩻
::math_gt_question::⩼
::math_leq_slanted::⩽
::math_geq_slanted::⩾
::math_leq_slanted_dot::⩿

;################################################                    MISCELLANEOUS TECHNICAL
::tech_lceil::⌈
::tech_rceil::⌉
::tech_lfloor::⌊
::tech_rfloor::⌋

;################################################                    ENCLOSED ALPHANUMERICALS
::circle00::⓪
::circle01::①
::circle02::②
::circle03::③
::circle04::④
::circle05::⑤
::circle06::⑥
::circle07::⑦
::circle08::⑧
::circle09::⑨
::circle10::⑩
::circle11::⑪
::circle12::⑫
::circle13::⑬
::circle14::⑭
::circle15::⑮
::circle16::⑯
::circle17::⑰
::circle18::⑱
::circle19::⑲
::circle20::⑳

::circle_capital_a::Ⓐ
::circle_capital_b::Ⓑ
::circle_capital_c::Ⓒ
::circle_capital_d::Ⓓ
::circle_capital_e::Ⓔ
::circle_capital_f::Ⓕ
::circle_capital_g::Ⓖ
::circle_capital_h::Ⓗ
::circle_capital_i::Ⓘ
::circle_capital_j::Ⓙ
::circle_capital_k::Ⓚ
::circle_capital_l::Ⓛ
::circle_capital_m::Ⓜ
::circle_capital_n::Ⓝ
::circle_capital_o::Ⓞ
::circle_capital_p::Ⓟ
::circle_capital_q::Ⓠ
::circle_capital_r::Ⓡ
::circle_capital_s::Ⓢ
::circle_capital_t::Ⓣ
::circle_capital_u::Ⓤ
::circle_capital_v::Ⓥ
::circle_capital_w::Ⓦ
::circle_capital_x::Ⓧ
::circle_capital_y::Ⓨ
::circle_capital_z::Ⓩ
::circle_lowercase_a::ⓐ
::circle_lowercase_b::ⓑ
::circle_lowercase_c::ⓒ
::circle_lowercase_d::ⓓ
::circle_lowercase_e::ⓔ
::circle_lowercase_f::ⓕ
::circle_lowercase_g::ⓖ
::circle_lowercase_h::ⓗ
::circle_lowercase_i::ⓘ
::circle_lowercase_j::ⓙ
::circle_lowercase_k::ⓚ
::circle_lowercase_l::ⓛ
::circle_lowercase_m::ⓜ
::circle_lowercase_n::ⓝ
::circle_lowercase_o::ⓞ
::circle_lowercase_p::ⓟ
::circle_lowercase_q::ⓠ
::circle_lowercase_r::ⓡ
::circle_lowercase_s::ⓢ
::circle_lowercase_t::ⓣ
::circle_lowercase_u::ⓤ
::circle_lowercase_v::ⓥ
::circle_lowercase_w::ⓦ
::circle_lowercase_x::ⓧ
::circle_lowercase_y::ⓨ
::circle_lowercase_z::ⓩ

;################################################                    NUMBER FORMS (AND FRACTIONS)
::frac_one_fourth::¼
::frac_one_half::½
::frac_three_fourths::¾
::frac_one_seventh::⅐
::frac_one_ninth::⅑
::frac_one_tenth::⅒
::frac_one_third::⅓
::frac_two_thirds::⅔
::frac_one_fifth::⅕
::frac_two_fifths::⅖
::frac_three_fifths::⅗
::frac_four_fifths::⅘
::frac_one_sixth::⅙
::frac_five_sixths::⅚
::frac_one_eighth::⅛
::frac_three_eighths::⅜
::frac_five_eighths::⅝
::frac_seven_eighths::⅞
::frac_one_empty::⅟
::frac_zero_thirds::↉

::fr14::¼
::fr12::½
::fr34::¾
::fr17::⅐
::fr19::⅑
::fr110::⅒
::fr13::⅓
::fr23::⅔
::fr15::⅕
::fr25::⅖
::fr35::⅗
::fr45::⅘
::fr16::⅙
::fr56::⅚
::fr18::⅛
::fr38::⅜
::fr58::⅝
::fr78::⅞
::fr10::⅟
::fr03::↉

;################################################                    ARROWS
::arrow_left::← ;Arrows
::arrow_up::↑
::arrow_right::→
::arrow_down::↓
::arrow_horizontal::↔
::arrow_vertical::↕
::arrow_northwest::↖
::arrow_northeast::↗
::arrow_southeast::↘
::arrow_southwest::↙
::arrow_not_left::↚
::arrow_not_right::↛
::arrow_twohead_left::↞
::arrow_twohead_up::↟
::arrow_twohead_right::↠
::arrow_twohead_down::↡
::arrow_tail_left::↢
::arrow_tail_right::↣
::arrow_frombar_left::↤
::arrow_frombar_up::↥
::arrow_frombar_right::↦
::arrow_frombar_down::↧
::arrow_not_horizontal::↮
::arrow_zigzag::↯
::arrow_ccw::↺
::arrow_cw::↻
::arrow_harpoon_lu::↼
::arrow_harpoon_ld::↽
::arrow_harpoon_ur::↾
::arrow_harpoon_ul::↿
::arrow_harpoon_ru::⇀
::arrow_harpoon_rd::⇁
::arrow_harpoon_dr::⇂
::arrow_harpoon_dl::⇃
::arrow_two_rl::⇄
::arrow_two_ud::⇅
::arrow_two_lr::⇆
::arrow_two_ll::⇇
::arrow_two_uu::⇈
::arrow_two_rr::⇉
::arrow_two_dd::⇊
::arrow_two_hlr::⇋
::arrow_two_hrl::⇌
::arrow_double_not_left::⇍
::arrow_double_not_horizontal::⇎
::arrow_double_not_right::⇏
::arrow_double_left::⇐
::arrow_double_up::⇑
::arrow_double_right::⇒
::arrow_double_down::⇓
::arrow_double_horizontal::⇔
::arrow_double_vertical::⇕
::arrow_double_northwest::⇖
::arrow_double_northeast::⇗
::arrow_double_southeast::⇘
::arrow_double_southwest::⇙
::arrow_triple_left::⇚
::arrow_triple_right::⇛
::arrow_doublestroke_up::⇞
::arrow_doublestroke_down::⇟
::arrow_tobar_left::⇤
::arrow_tobar_right::⇥
::arrow_white_left::⇦
::arrow_white_up::⇧
::arrow_white_right::⇨
::arrow_white_down::⇩
::arrow_white:vertical::⇳
::arrow_two_du::⇵
::arrow_three_rrr::⇶
::arrow_stroke_left::⇷
::arrow_stroke_right::⇸
::arrow_stroke_horizontal::⇹
::arrow_doublestroke_left::⇺
::arrow_doublestroke_right::⇻
::arrow_doublestroke_horizontal::⇼

::arrow_quad_up::⟰ ;Supplemental Arrows-A
::arrow_quad_down::⟱

::arrow_twohead_stroke_right::⤀ ;Supplemental Arrows-B
::arrow_twohead_doublestroke_right::⤁
::arrow_double_stroke_left::⤂
::arrow_double_stroke_right::⤃
::arrow_double_stroke_horizontal::⤄
::arrow_twohead_frombar_right::⤅
::arrow_stroke_down::⤈
::arrow_stroke_up::⤉
::arrow_triple_up::⤊
::arrow_triple_down::⤋
::arrow_tobar_up::⤒
::arrow_tobar_down::⤓
::arrow_tail_stroke_right::⤔
::arrow_tail_doublestroke_right::⤕
::arrow_twohead_tail_right::⤖
::arrow_twohead_tail_stroke_right::⤗
::arrow_twohead_tail_doublestroke_right::⤘
::arrow_reverse_right::⤙
::arrow_reverse_left::⤚
::arrow_reverse_twohead_right::⤛
::arrow_reverse_twohead_left::⤜
::arrow_nwse::⤡
::arrow_swne::⤢
::arrow_two_nwne::⤧
::arrow_two_nese::⤨
::arrow_two_swse::⤩
::arrow_two_nwsw::⤪

::arrow_three_lll::⬱ ;Miscellaneous Symbols and Arrows
::arrow_twohead_stroke_left::⬴
::arrow_twohead_doublestroke_left::⬵
::arrow_twohead_frombar_left::⬶
::arrow_tail_stroke_left::⬹
::arrow_tail_doublestroke_left::⬺
::arrow_twohead_tail_left::⬻
::arrow_twohead_tail_stroke_left::⬼
::arrow_twohead_tail_doublestroke_left::⬽
::arrow_quad_left::⭅
::arrow_quad_right::⭆

;################################################                    MISCELLANEOUS SYMBOLS
::misc_aries::♈
::misc_taurus::♉
::misc_gemini::♊
::misc_cancer::♋
::misc_leo::♌
::misc_virgo::♍
::misc_libra::♎
::misc_scorpius::♏
::misc_sagittarius::♐
::misc_capricorn::♑
::misc_aquarius::♒
::misc_pisces::♓
::misc_ophiuchus::⛎

;################################################                    KATAKANA
::kataa::ア
::katai::イ
::katau::ウ
::katae::エ
::katao::オ
::kataka::カ
::kataga::ガ
::kataki::キ
::katagi::ギ
::kataku::ク
::katagu::グ
::katake::ケ
::katage::ゲ
::katako::コ
::katago::ゴ
::katasa::サ
::kataza::ザ
::katasi::シ
::katazi::ジ
::katasu::ス
::katazu::ズ
::katase::セ
::kataze::ゼ
::kataso::ソ
::katazo::ゾ
::katata::タ
::katada::ダ
::katati::チ
::katadi::ヂ
::katatu::ツ
::katadu::ヅ
::katate::テ
::katade::デ
::katato::ト
::katado::ド
::katana::ナ
::katani::ニ
::katanu::ヌ
::katane::ネ
::katano::ノ
::kataha::ハ
::kataba::バ
::katapa::パ
::katahi::ヒ
::katabi::ビ
::katapi::ピ
::katahu::フ
::katabu::ブ
::katapu::プ
::katahe::ヘ
::katabe::ベ
::katape::ペ
::kataho::ホ
::katabo::ボ
::katapo::ポ
::katama::マ
::katami::ミ
::katamu::ム
::katame::メ
::katamo::モ
::kataya::ヤ
::katayu::ユ
::katayo::ヨ
::katara::ラ
::katari::リ
::kataru::ル
::katare::レ
::kataro::ロ
::katawa::ワ
::katawi::ヰ
::katawe::ヱ
::katawo::ヲ
::katan::ン
::katavu::ヴ
::katava::ヷ
::katavi::ヸ
::katave::ヹ
::katavo::ヺ
::kataiter::ヽ
::katavoiced_iter::ヾ

;################################################                    GENERAL AND SUPPLEMENTAL PUNCTUATION
::punc_endash::–
::punc_emdash::—
::punc_quote_left::‘
::punc_quote_right::’
::punc_quote_lower_left::‚
::punc_quote_reversed_left::‛
::punc_doublequote_left::“
::punc_doublequote_right::”
::punc_doublequote_lower_left::„
::punc_doublequote_reversed_left::‟
::punc_dagger::†
::punc_doubledagger::‡
::punc_ellipsis::…
::punc_permille::‰
::punc_pertenthousand::‱
::punc_prime::′
::punc_doubleprime::″
::punc_tripleprime::‴
::punc_reversed_prime::‵
::punc_reversed_doubleprime::‶
::punc_reversed_tripleprime::‷
::punc_quote_angle_left::‹
::punc_quote_angle_right::›
::punc_referencemark::※
::punc_double_exclamation::‼
::punc_interrobang::‽
::punc_overline::‾
::punc_asterism::⁂
::punc_sqbracket_quill_left::⁅
::punc_sqbracket_quill_right::⁆
::punc_double_question::⁇
::punc_question_exclamation::⁈
::punc_exclamation_question::⁉
::punc_double_asterisk::⁑
::punc_quadprime::⁗
::punc_tricolon::⁝
::punc_tetracolon::⁞

::punc_reversed_interrobang::⸘
::punc_doubleparen_left::⸨
::punc_doubleparen_right::⸩
::punc_twoemdash::⸺
::punc_threeemdash::⸻
::punc_hexacolon::⸽
::punc_tripledagger::⹋

::punc_enquad::
::punc_emquad::
::punc_enspace::
::punc_emspace::
::punc_threeperem::
::punc_fourperem::
::punc_sixperem::
::punc_thinspace::
::punc_hairspace::
::punc_zwspace::
::punc_zwnj::
::punc_zwj::
::punc_narrow_nbsp::

::punc_tironianet::⁊
::punc_double_underscore::‗
::punc_caret::‸
::punc_threedots::⁖
::punc_fourdots::⁘
::punc_fivedots::⁙
::punc_twodots::⁚

;################################################                    BRACKETS AND PARENTHESES
::bracket_anglequote_double_left::«
::bracket_anglequote_double_right::»
::bracket_anglequote_left::‹
::bracket_anglequote_right::›
::bracket_square_white_left::⟦
::bracket_square_white_right::⟧
::bracket_angle_math_left::⟨
::bracket_angle_math_right::⟩
::bracket_angle_math_double_left::⟪
::bracket_angle_math_double_right::⟫
::bracket_tortoise_white_left::⟬
::bracket_tortoise_white_right::⟭
::bracket_flattened_left::⟮
::bracket_flattened_right::⟯
::bracket_curly_white_left::⦃
::bracket_curly_white_right::⦄
::bracket_white_left::⦅
::bracket_white_right::⦆
::bracket_angle_dot_left::⦑
::bracket_angle_dot_right::⦒
::bracket_inequality_left::⦓
::bracket_inequality_right::⦔
::bracket_inequality_double_left::⦕
::bracket_inequality_double_right::⦖
::bracket_curved_left::⧼
::bracket_curved_right::⧽
::bracket_square_quill_left::⁅
::bracket_square_quill_right::⁆
::bracket_double_left::⸨
::bracket_double_right::⸩
::bracket_tortoise_left::〔
::bracket_tortoise_right::〕
::bracket_lens_left::〖
::bracket_lens_right::〗
::bracket_asian_angle_left::〈
::bracket_asian_angle_right::〉
::bracket_asian_angle_double_left::《
::bracket_asian_angle_double_right::》
::bracket_asian_corner_left::「
::bracket_asian_corner_right::」
::bracket_asian_corner_white_left::『
::bracket_asian_corner_white_right::』
::bracket_asian_lens_black_left::【
::bracket_asian_lens_black_right::】

;################################################                    MATHEMATICAL ALPHANUMERICS
::_bba::𝔸
::_bbb::𝔹
::_bbc::ℂ
::_bbd::𝔻
::_bbe::𝔼
::_bbf::𝔽
::_bbg::𝔾
::_bbh::ℍ
::_bbi::𝕀
::_bbj::𝕁
::_bbk::𝕂
::_bbl::𝕃
::_bbm::𝕄
::_bbn::ℕ
::_bbo::𝕆
::_bbp::ℙ
::_bbq::ℚ
::_bbr::ℝ
::_bbs::𝕊
::_bbt::𝕋
::_bbu::𝕌
::_bbv::𝕍
::_bbw::𝕎
::_bbx::𝕏
::_bby::𝕐
::_bbz::ℤ
::_bb0::𝟘
::_bb1::𝟙
::_bb2::𝟚
::_bb3::𝟛
::_bb4::𝟜
::_bb5::𝟝
::_bb6::𝟞
::_bb7::𝟟
::_bb8::𝟠
::_bb9::𝟡

::_fra::𝔄
::_frb::𝔅
::_frc::ℭ
::_frd::𝔇
::_fre::𝔈
::_frf::𝔉
::_frg::𝔊
::_frh::ℌ
::_fri::ℑ
::_frj::𝔍
::_frk::𝔎
::_frl::𝔏
::_frm::𝔐
::_frn::𝔑
::_fro::𝔒
::_frp::𝔓
::_frq::𝔔
::_frr::ℜ
::_frs::𝔖
::_frt::𝔗
::_fru::𝔘
::_frv::𝔙
::_frw::𝔚
::_frx::𝔛
::_fry::𝔜
::_frz::ℨ

::dotless_i::ı
::dotless_j::ȷ

::_scac::𝒜
::_scbc::ℬ
::_sccc::𝒞
::_scdc::𝒟
::_scec::ℰ
::_scfc::ℱ
::_scgc::𝒢
::_schc::ℋ
::_scic::ℐ
::_scjc::𝒥
::_sckc::𝒦
::_sclc::ℒ
::_scmc::ℳ
::_scnc::𝒩
::_scoc::𝒪
::_scpc::𝒫
::_scqc::𝒬
::_scrc::ℛ
::_scsc::𝒮
::_sctc::𝒯
::_scuc::𝒰
::_scvc::𝒱
::_scwc::𝒲
::_scxc::𝒳
::_scyc::𝒴
::_sczc::𝒵
::_sca::𝒶
::_scb::𝒷
::_scc::𝒸
::_scd::𝒹
::_sce::ℯ
::_scf::𝒻
::_scg::ℊ
::_sch::𝒽
::_sci::𝒾
::_scj::𝒿
::_sck::𝓀
::_scl::𝓁
::_scm::𝓂
::_scn::𝓃
::_sco::ℴ
::_scp::𝓅
::_scq::𝓆
::_scr::𝓇
::_scs::𝓈
::_sct::𝓉
::_scu::𝓊
::_scv::𝓋
::_scw::𝓌
::_scx::𝓍
::_scy::𝓎
::_scz::𝓏

;################################################                    SUPERSCRIPTS AND SUBSCRIPTS
::_sup0::⁰
::_sup1::¹
::_sup2::²
::_sup3::³
::_sup4::⁴
::_sup5::⁵
::_sup6::⁶
::_sup7::⁷
::_sup8::⁸
::_sup9::⁹

::_sub0::₀
::_sub1::₁
::_sub2::₂
::_sub3::₃
::_sub4::₄
::_sub5::₅
::_sub6::₆
::_sub7::₇
::_sub8::₈
::_sub9::₉

::_sub10::⏨

::_supa::ᵃ
::_supb::ᵇ
::_supc::ᶜ
::_supd::ᵈ
::_supe::ᵉ
::_supf::ᶠ
::_supg::ᵍ
::_suph::ʰ
::_supi::ⁱ
::_supj::ʲ
::_supk::ᵏ
::_supl::ˡ
::_supm::ᵐ
::_supn::ⁿ
::_supo::ᵒ
::_supp::ᵖ
::_supr::ʳ
::_sups::ˢ
::_supt::ᵗ
::_supu::ᵘ
::_supv::ᵛ
::_supw::ʷ
::_supx::ˣ
::_supy::ʸ
::_supz::ᶻ

;################################################                    NUMBER FORMS (ROMAN NUMERALS)
::roman_1::Ⅰ
::roman_2::Ⅱ
::roman_3::Ⅲ
::roman_4::Ⅳ
::roman_5::Ⅴ
::roman_6::Ⅵ
::roman_7::Ⅶ
::roman_8::Ⅷ
::roman_9::Ⅸ
::roman_10::Ⅹ
::roman_11::Ⅺ
::roman_12::Ⅻ
::roman_50::Ⅼ
::roman_100::Ⅽ
::roman_500::Ⅾ
::roman_1000::Ⅿ
::roman_5000::ↁ
::roman_10000::ↂ
::roman_50000::ↇ
::roman_100000::ↈ

;################################################                    CYRILLIC
::cyra::а
::cyrbe::б
::cyrve::в
::cyrghe::г
::cyrde::д
::cyrie::е
::cyrzhe::ж
::cyrze::з
::cyri::и
::cyrishort::й
::cyrka::к
::cyrel::л
::cyrem::м
::cyren::н
::cyro::о
::cyrpe::п
::cyrer::р
::cyres::с
::cyrte::т
::cyru::у
::cyref::ф
::cyrha::х
::cyrtse::ц
::cyrche::ч
::cyrsha::ш
::cyrshcha::щ
::cyrhard::ъ
::cyryeru::ы
::cyrsoft::ь
::cyre::э
::cyryu::ю
::cyrya::я

::cyrie_grave::ѐ
::cyrio::ё
::cyrdje::ђ
::cyrgje::ѓ
::cyrukrie::є
::cyrdze::ѕ
::cyrukri::і
::cyryi::ї
::cyrje::ј
::cyrlje::љ
::cyrhje::њ
::cyrtshe::ћ
::cyrkje::ќ
::cyri_grave::ѝ
::cyrushort::ў
::cyrdzhe::џ

::cyromega::ѡ
::cyryat::ѣ
::cyreiota::ѥ
::cyrlittleyus::ѧ
::cyrlittleyus_iota::ѩ
::cyrbigyus::ѫ
::cyrbigyus_iota::ѭ
::cyrksi::ѯ
::cyrpsi::ѱ
::cyrfita::ѳ
::cyrizhitsa::ѵ
::cyrizhitsa_doublegrave::ѷ
::cyruk::ѹ
::cyromega_round::ѻ
::cyromega_titlo::ѽ
::cyrot::ѿ
::cyrkoppa::ҁ

::cyrishort_tail::ҋ
::cyrsemisoft::ҍ
::cyrer_tick::ҏ
::cyrghe_upturn::ґ
::cyrghe_stroke::ғ
::cyrghe_middlehook::ҕ
::cyrzhe_descender::җ
::cyrze_descender::ҙ
::cyrka_descender::қ
::cyrka_verticalstroke::ҝ
::cyrka_stroke::ҟ
::cyrka_bashkir::ҡ
::cyren_descender::ң
::cyrlig_eng_he::ҥ
::cyrpe_middlehook::ҧ
::cyrha_abkhasian::ҩ
::cyres_descender::ҫ
::cyrte_descender::ҭ
::cyru_straight::ү
::cyru_stroke::ұ
::cyrha_descender::ҳ
::cyrlig_te_tse::ҵ
::cyrche_descender::ҷ
::cyrche_verticalstroke::ҹ
::cyrshha::һ
::cyrche_abkhasian::ҽ
::cyrche_abkhasian_descender::ҿ
::cyrzhe_breve::ӂ
::cyrka_hook::ӄ
::cyrel_tail::ӆ
::cyren_hook::ӈ
::cyren_tail::ӊ
::cyrche_khakassian::ӌ
::cyrem_tail::ӎ
::cyrpalochka::ӏ
::cyra_breve::ӑ
::cyra_diaeresis::ӓ
::cyrlig_a_ie::ӕ
::cyrie_breve::ӗ
::cyrschwa::ә
::cyrschwa_diaeresis::ӛ
::cyrzhe_diaeresis::ӝ
::cyrze_diaeresis::ӟ
::cyrdze_abkhasian::ӡ
::cyri_macron::ӣ
::cyri_diaeresis::ӥ
::cyro_diaeresis::ӧ
::cyro_bar::ө
::cyro_bar_diaeresis::ӫ
::cyre_diaeresis::ӭ
::cyru_macron::ӯ
::cyru_diaeresis::ӱ
::cyru_doublegrave::ӳ
::cyrche_diaeresis::ӵ
::cyrghe_descender::ӷ
::cyryeru_diaeresis::ӹ
::cyrghe_stroke_hook::ӻ
::cyrha_hook::ӽ
::cyrha_stroke::ӿ

::cyrde_komi::ԁ
::cyrdje_komi::ԃ
::cyrzje_komi::ԅ
::cyrdzje_komi::ԇ
::cyrlje_komi::ԉ
::cyrnje_komi::ԋ
::cyrsje_komi::ԍ
::cyrtje_komi::ԏ
::cyrze_reversed::ԑ
::cyrel_kook::ԓ
::cyrlha::ԕ
::cyrrha::ԗ
::cyryae::ԙ
::cyrqa::ԛ
::cyrwe::ԝ
::cyrka_aleut::ԟ
::cyrel_middlehook::ԡ
::cyren_middlehook::ԣ
::cyrpe_descender::ԥ
::cyrshha_descender::ԧ
::cyren_lefthook::ԩ
::cyrdzzhe::ԫ
::cyrdche::ԭ
::cyrel_descender::ԯ


::cyrzemlya::ꙁ
::cyrdzelo::ꙃ
::cyrdze_reversed::ꙅ
::cyriota::ꙇ
::cyrdjerv::ꙉ
::cyruk_monograph::ꙋ
::cyromega_broad::ꙍ
::cyryer_neutral::ꙏ
::cyryeru_yer::ꙑ
::cyryat_iota::ꙓ
::cyryu_reversed::ꙕ
::cyra_iota::ꙗ
::cyrlittleyus_closed::ꙙ
::cyryus_blended::ꙛ
::cyrlittleyus_closed_iota::ꙝ
::cyryn::ꙟ
::cyrtse_reversed::ꙡ
::cyrde_soft::ꙣ
::cyrel_soft::ꙥ
::cyrem_soft::ꙧ
::cyro_monocular::ꙩ
::cyro_binocular::ꙫ
::cyro_monocular_double::ꙭ
::cyro_multiocular::ꙮ
::cyrdwe::ꚁ
::cyrdzwe::ꚃ
::cyrzhwe::ꚅ
::cyrcche::ꚇ
::cyrdzze::ꚉ
::cyrte_middlehook::ꚋ
::cyrtwe::ꚍ
::cyrtswe::ꚏ
::cyrtsse::ꚑ
::cyrtche::ꚓ
::cyrhwe::ꚕ
::cyrshwe::ꚗ
::cyro_double::ꚙ
::cyro_cross::ꚛ

;################################################                    LATIN
::lattimes::× ;Latin-1 Supplement
::lata_grave::à
::lata_acute::á
::lata_circumflex::â
::lata_tilde::ã
::lata_diaeresis::ä
::lata_ring::å
::latae::æ
::latc_cedilla::ç
::late_grave::è
::late_acute::é
::late_circumflex::ê
::late_diaeresis::ë
::lati_grave::ì
::lati_acute::í
::lati_circumflex::î
::lati_diaeresis::ï
::lateth::ð
::latn_tilde::ñ
::lato_grave::ò
::lato_acute::ó
::lato_circumflex::ô
::lato_tilde::õ
::lato_diaeresis::ö
::latdivides::÷
::lato_stroke::ø
::latu_grave::ù
::latu_acute::ú
::latu_circumflex::û
::latu_diaeresis::ü
::laty_acute::ý
::latthorn::þ
::laty_diaeresis::ÿ

::lata_macron::ā ;Latin Extended-A
::lata_breve::ă
::lata_ogonek::ą
::latc_acute::ć
::latc_circumflex::ĉ
::latc_dotabove::ċ
::latc_caron::č
::latd_caron::ď
::latd_stroke::đ
::late_mactron::ē
::late_breve::ĕ
::late_dotabove::ė
::late_ogonek::ę
::late_caron::ě
::latg_circumflex::ĝ
::latg_breve::ğ
::latg_dotabove::ġ
::latg_cedilla::ģ
::lath_circumflex::ĥ
::lath_stroke::ħ
::lati_tilde::ĩ
::lati_macron::ī
::lati_breve::ĭ
::lati_ogonek::į
::lati_dotless::ı
::latlig_i_j::ĳ
::latj_circumflex::ĵ
::latk_cedilla::ķ
::latkra::ĸ
::latl_acute::ĺ
::latl_cedilla::ļ
::latl_caron::ľ
::latl_middledot::ŀ
::latl_stroke::ł
::latn_acute::ń
::latn_cedilla::ņ
::latn_caron::ň
::latn_apostrophe::ŉ
::lateng::ŋ
::lato_macron::ō
::lato_breve::ŏ
::lato_doubleacute::ő
::latlig_o_e::œ
::latr_acute::ŕ
::latr_cedilla::ŗ
::latr_caron::ř
::lats_acute::ś
::lats_circumflex::ŝ
::lats_cedilla::ş
::lats_caron::š
::latt_cedilla::ţ
::latt_caron::ť
::latt_stroke::ŧ
::latu_tilde::ũ
::latu-macron::ū
::latu_breve::ŭ
::latu_ring::ů
::latu_doubleacute::ű
::latu_ogonek::ų
::latw_circumflex::ŵ
::laty_circumflex::ŷ
::latz_acute::ź
::latz_dotabove::ż
::latz_caron::ž
::lats_long::ſ

::latb_stroke::ƀ ;Latin Extended-B
::latb_hook::Ɓ ;<--Capital
::latb_topbar::ƃ
::lattone_six::ƅ
::lato_open::Ɔ
::latc_hook::ƈ
::latd_african::Ɖ ;<--Capital
::latd_hook::Ɗ ;<--Capital
::latd_topbar::ƌ
::latdelta_turned::ƍ
::latschwa::Ə
::late_open::Ɛ
::latf_hook::ƒ
::latg_hook::Ɠ ;<--Capital
::latgamma::Ɣ
::lathwair::ƕ
::latiota::Ɩ ;<--Capital
::lati_stroke::Ɨ ;<--Capital
::latk_hook::ƙ
::latl_bar::ƚ
::latlambda_stroke::ƛ
::latm_turned::Ɯ
::latn_lefthook::Ɲ
::latn_longrightleg::ƞ
::lato_middletilde::Ɵ ;<--Capital
::lato_horn::ơ
::latgha::ƣ
::latp_hook::ƥ
::latyr::Ʀ ;<--Capital
::lattone_two::ƨ
::latesh::Ʃ ;<--Capital
::latesh_loop::ƪ
::latt_palatalhook::ƫ
::latt_hook::ƭ
::latt_retrolfexhook::Ʈ ;<--Capital
::latu_horn::ư
::latupsilon::Ʊ ;<--Capital
::latv_hook::Ʋ
::laty_hook::ƴ
::latz_stroke::ƶ
::latezh::Ʒ ;<--Capital
::latezh_reversed::ƹ
::latezh_tail::ƺ
::lattwo_stroke::ƻ
::lattone_five::ƽ
::latglottalstop_inverted_stroke::ƾ
::latwynn::ƿ
::latclick_dental::ǀ
::latclick_lateral::ǁ
::latclick_alveolar::ǂ
::latclick_retroflex::ǃ
::latdz_caron_capital::ǅ
::latdz_caron::ǆ
::latlj_capital::ǈ
::latlj::ǉ
::latnj_capital::ǋ
::latnj::ǌ
::lata_caron::ǎ
::lati_caron::ǐ
::lato_caron::ǒ
::latu_caron::ǔ
::latu_diaeresis_macron::ǖ
::latu_diaeresis_acute::ǘ
::latu_diaeresis_caron::ǚ
::latu_diaeresis_grave::ǜ
::late_turned::ǝ
::lata_diaeresis_macron::ǟ
::lata_dotavobe_macron::ǡ
::latae_macron::ǣ
::latg_stroke::ǥ
::latg_caron::ǧ
::latk_caron::ǩ
::lato_ogonek::ǫ
::lato_ogonek_macron::ǭ
::latezh_caron::ǯ
::latj_caron::ǰ
::latdz_capital::ǲ
::latdz::ǳ
::latg_acute::ǵ
::latn_grave::ǹ
::lata_ring_acute::ǻ
::latae_acute::ǽ
::lato_stroke_acute::ǿ
::lata_doublegrave::ȁ
::lata_invertedbreve::ȃ
::late_doublegrave::ȅ
::late_invertedbreve::ȇ
::lati_doublegrave::ȉ
::lati_invertedbreve::ȋ
::lato_doublegrave::ȍ
::lato_invertedbreve::ȏ
::latr_doublegrave::ȑ
::latr_invertedbreve::ȓ
::latu_doublegrave::ȕ
::latu_invertedbreve::ȗ
::lats_comma::ș
::latt_comma::ț
::latyogh::ȝ
::lath_caron::ȟ
::latd_curl::ȡ
::latou::ȣ
::latz_hook::ȥ
::lata_dotabove::ȧ
::late_cedilla::ȩ
::lato_diaeresis_macron::ȫ
::lato_tilde_macron::ȭ
::lato_dotabove::ȯ
::lato_dotabove_macron::ȱ
::laty_macron::ȳ
::latl_curl::ȴ
::latn_curl::ȵ
::latt_curl::ȶ
::latj_dotless::ȷ
::latlig_d_b::ȸ
::latlig_q_p::ȹ
;::lata_stroke::Ⱥ ;→LatExtC
::latc_stroke::ȼ
::latl_bar::Ƚ
;::latt_stroke::Ⱦ ;→LatExtC
::lats_swashtail::ȿ
::latz_swashtail::ɀ
::latglottalstop::ɂ
::latu_bar::Ʉ
::latv_turned::Ʌ
::late_stroke::ɇ
::latj_stroke::ɉ
::latq_hooktail::ɋ
::latr_stroke::ɍ
::laty_stroke::ɏ

::latl_doublebar::ⱡ ;Latin Extended-C
::latl_tilde::Ɫ ;<--Capital
::latp_stroke::Ᵽ ;<--Capital
::latr_tail::Ɽ ;<--Capital
::lata_stroke::ⱥ
::latt_stroke::ⱦ
::lath_descender::ⱨ
::latk_descender::ⱪ
::latz_descender::ⱬ
::latalpha::Ɑ ;<--Capital
::latm_hook::Ɱ ;<--Capital
::lata_turned::Ɐ ;<--Capital
::latalhpa_turned::Ɒ ;<--Capital
::latv_righthook::ⱱ
::latw_hook::ⱳ
::latv_curl::ⱴ
::lath_half::ⱶ
::latphi_tailless::ⱷ
::late_notch::ⱸ
::latr_turned_tail::ⱹ
::lato_lowring::ⱺ
::late_turned_smallcapital::ⱻ

::latalef_egyptological::ꜣ ;Latin Extended-D
::latain_egyptological::ꜥ
::latheng::ꜧ
::lattz::ꜩ
::lattresillo::ꜫ
::latcuatrillo::ꜭ
::latcuatrillo_comma::ꜯ
::latf_smallcapital::ꜰ
::lats_smallcapital::ꜱ
::lataa::ꜳ
::latao::ꜵ
::latau::ꜷ
::latav::ꜹ
::latav_bar::ꜻ
::latay::ꜽ
::latc_reversed_dot::ꜿ
::latk_stroke::ꝁ
::latk_diagonalstroke::ꝃ
::latk_stroke_diagonalstroke::ꝅ
::latl_broken::ꝇ
::latl_highstroke::ꝉ
::lato_longstroke::ꝋ
::lato_loop::ꝍ
::latoo::ꝏ
::latp_lowstroke::ꝑ
::latp_flourish::ꝓ
::latp_squirreltail::ꝕ
::latq_lowstroke::ꝗ
::latq_diagonalstroke::ꝙ
::latr_rotunda::ꝛ
::latrum_rotunda::ꝝ
::latv_diagonalstroke::ꝟ
::latvy::ꝡ
::latz_visigothic::ꝣ
::latthorn_stroke::ꝥ
::latthorn_lowstrokek::ꝧ
::latvend::ꝩ
::latet::ꝫ
::latis::ꝭ
::latcon::ꝯ
::latus::ꝰ
::latdum::ꝱ
::latlum::ꝲ
::latmum::ꝳ
::latnum::ꝴ
::latrum::ꝵ
::latrum_capital::ꝶ
::lattum::ꝷ
::latum::ꝸ
::latd_insular::ꝺ
::latf_insular::ꝼ
::latg_insular::ᵹ
::latg_insular_turned::ꝿ
::latl_turned::ꞁ
::latr_insular::ꞃ
::lats_insular::ꞅ
::latt_insular::ꞇ
::latmod_lowcircumflex::ꞈ
::latmod_colon::꞉
::latmod_shortequals::꞊
::latsaltillo::ꞌ
::lath_turned::ɥ
::latl_retroflexhook_belt::ꞎ
::latdot_sinological::ꞏ
::latn_descender::ꞑ
::latc_bar::ꞓ
::latc_palatalhook::ꞔ
::lath_palatalhook::ꞕ
::latb_flourish::ꞗ
::latf_stroke::ꞙ
::latae_volapuk::ꞛ
::latoe_volapuk::ꞝ
::latue_volapuk::ꞟ
::latg_obliquestroke::ꞡ
::latk_obliquestroke::ꞣ
::latn_obliquestroke::ꞥ
::latr_obliquestroke::ꞧ
::lats_obliquestroke::ꞩ
::lath_hook::ɦ
::late_open_reverse::ɜ
::latg_script::ɡ
::latl_belt::ɬ
::lati_smallcapital::Ɪ
::latq_smallcapital::ꞯ
::latk_turned::ʞ
::latt_turned::ʇ
::latj_crossedtail::Ʝ
::latchi_capital::Ꭓ
::latbeta_capital::Ꞵ
::latbeta::ꞵ
::latomega_capital::Ꞷ
::latomega::ꞷ
::latu_stroke_capital::Ꞹ
::latu_stroke::ꞹ
::lati_sideways::ꟷ
::latm_turned_smallcapital::ꟺ
::latf_turned::ꟻ
::latp_turned::ꟼ
::latm_inverted::ꟽ
::lati_longa::ꟾ
::latm_archaic::ꟿ

::latalpha_bar::ꬰ ;Latin Extended-E
::latlig_a_schwa_reversed::ꬱ
::late_blackletter::ꬲ
::late_bar::ꬳ
::late_flourish::ꬴ
::latf_lenis::ꬵ
::latg_crossedtail::ꬶ
::latlig_l_s_lazy_inverted::ꬷ
::latl_doublemiddletilde::ꬸ
::latl_middlering::ꬹ
::latm_crossedtail::ꬺ
::latn_crossedtail::ꬻ
::lateng_crossedtail::ꬼ
::lato_blackletter::ꬽ
::lato_blackletter_stroke::ꬾ
::lato_open_stroke::ꬿ
::latoe_inverted::ꭀ
::latoe_turned_stroke::ꭁ
::latoe_turned_horizontalstroke::ꭂ
::latlig_o_o_open_turned::ꭃ
::latlig_o_o_open_stroke_turned::ꭄ
::latr_stirrup::ꭅ
::latr_rightleg_smallcapital::ꭆ
::latr_nohandle::ꭇ
::latr_double::ꭈ
::latr_crossedtail::ꭉ
::latr_double_crossedtail::ꭊ
::latr_script::ꭋ
::latr_script_ring::ꭌ
::latesh_baseline::ꭍ
::latu_shortrightleg::ꭎ
::latu_shortrightleg_stroke::ꭏ
::latui::ꭐ
::latui_turned::ꭑ
::latu_lefthook::ꭒ
::latchi::ꭓ
::latchi_lowrightring::ꭔ
::latchi_lowleftserif::ꭕ
::latx_lowrightring::ꭖ
::latx_longleftleg::ꭗ
::latx_longleftleg_lowrightring::ꭘ
::latx_lowleftserif::ꭙ
::laty_shortrightleg::ꭚ
::latmod_breve_invertedbreve::꭛
::latyat_sakha::ꭠ
::late_iota::ꭡ
::latoe_open::ꭢ
::latuo::ꭣ
::latalpha_inverted::ꭤ
::latomega_smallcapital::ꭥ

;################################################                    MISCELLANEOUS TECHNICAL
::misc_paren_rlu::⎛
::misc_paren_rle::⎜
::misc_paren_rll::⎝
::misc_paren_rru::⎞
::misc_paren_rre::⎟
::misc_paren_rrl::⎠
::misc_paren_slu::⎡
::misc_paren_sle::⎢
::misc_paren_sll::⎣
::misc_paren_sru::⎤
::misc_paren_sre::⎥
::misc_paren_srl::⎦
::misc_paren_clu::⎧
::misc_paren_clm::⎨
::misc_paren_cll::⎩
::misc_paren_cle::⎪
::misc_paren_cru::⎫
::misc_paren_crm::⎬
::misc_paren_crl::⎭

;################################################                    HIRAGANA

::hiraa::あ
::hirai::い
::hirau::う
::hirae::え
::hirao::お
::hiraka::か
::hiraga::が
::hiraki::き
::hiragi::ぎ
::hiraku::く
::hiragu::ぐ
::hirake::け
::hirage::げ
::hirako::こ
::hirago::ご
::hirasa::さ
::hiraza::ざ
::hirasi::し
::hirazi::じ
::hirasu::す
::hirazu::ず
::hirase::せ
::hiraze::ぜ
::hiraso::そ
::hirazo::ぞ
::hirata::た
::hirada::だ
::hirati::ち
::hiradi::ぢ
::hiratu::つ
::hiradu::づ
::hirate::て
::hirade::で
::hirato::と
::hirado::ど
::hirana::な
::hirani::に
::hiranu::ぬ
::hirane::ね
::hirano::の
::hiraha::は
::hiraba::ば
::hirapa::ぱ
::hirahi::ひ
::hirabi::び
::hirapi::ぴ
::hirahu::ふ
::hirabu::ぶ
::hirapu::ぷ
::hirahe::へ
::hirabe::べ
::hirape::ぺ
::hiraho::ほ
::hirabo::ぼ
::hirapo::ぽ
::hirama::ま
::hirami::み
::hiramu::む
::hirame::め
::hiramo::も
::hiraya::や
::hirayu::ゆ
::hirayo::よ
::hirara::ら
::hirari::り
::hiraru::る
::hirare::れ
::hiraro::ろ
::hirawa::わ
::hirawi::ゐ
::hirawe::ゑ
::hirawo::を
::hiran::ん
::hiravu::ゔ
::hiravoiced::゛
::hirasemivoiced::゜
::hiraiter::ゝ
::hiravoicediter::ゞ
::hirayori::ゟ

;################################################                    ALCHEMICAL SYMBOLS
::alch_quintessence::🜀
::alch_air::🜁
::alch_fire::🜂
::alch_earth::🜃
::alch_water::🜄
::alch_aquafortis::🜅
::alch_aquaregia::🜆
::alch_aquaregia_alt::🜇
::alch_aquavitae::🜈
::alch_aquavitae_alt::🜉
::alch_vinegar::🜊
::alch_vinegar_alt::🜋
::alch_vinegar_alt2::🜌
::alch_sulfur::🜍
::alch_philosopherssulfur::🜎
::alch_blacksulfur::🜏
::alch_mercurysublimate::🜐
::alch_mercurysublimate_alt::🜑
::alch_mercurysublimate_alt2::🜒
::alch_cinnabar::🜓
::alch_salt::🜔
::alch_nitre::🜕
::alch_vitriol::🜖
::alch_vitriol_alt::🜗
::alch_rocksalt::🜘
::alch_rocksalt_alt::🜙
::alch_gold::🜚
::alch_silver::🜛
::alch_ironore::🜜
::alch_ironore_alt::🜝
::alch_ironcrocus::🜞
::alch_ironregulus::🜟
::alch_copperore::🜠
::alch_ironcopperore::🜡
::alch_coppersublimate::🜢
::alch_coppercrocus::🜣
::alch_coppercrocus_alt::🜤
::alch_copperantimoniate::🜥
::alch_copperantimoniatesalt::🜦
::alch_coppersaltsublimate::🜧
::alch_verdigris::🜨
::alch_tinore::🜩
::alch_leadore::🜪
::alch_antimonyore::🜫
::alch_antimonysublimate::🜬
::alch_antimonysalt::🜭
::alch_antimonysaltsublimate::🜮
::alch_antimonyvinegar::🜯
::alch_antimonyregulus::🜰
::alch_antimonyregulus_alt::🜱
::alch_regulus::🜲
::alch_regulus_alt::🜳
::alch_regulus_alt2::🜴
::alch_regulus_alt3::🜵
::alch_alkali::🜶
::alch_alkaly_alt::🜷
::alch_marcasite::🜸
::alch_salammoniac::🜹
::alch_arsenic::🜺
::alch_realgar::🜻
::alch_realgar_alt::🜼
::alch_auripigment::🜽
::alch_bismuthore::🜾
::alch_tartar::🜿
::alch_tartar_alt::🝀
::alch_quicklime::🝁
::alch_borax::🝂
::alch_borax_alt::🝃
::alch_borax_alt2::🝄
::alch_alum::🝅
::alch_oil::🝆
::alch_spirit::🝇
::alch_tincture::🝈
::alch_gum::🝉
::alch_wax::🝊
::alch_powder::🝋
::alch_calx::🝌
::alch_tutty::🝍
::alch_caputmortuum::🝎
::alch_jovescepter::🝏
::alch_caduceus::🝐
::alch_trident::🝑
::alch_tridentstarred::🝒
::alch_lodestone::🝓
::alch_soap::🝔
::alch_urine::🝕
::alch_horsedung::🝖
::alch_ash::🝗
::alch_potash::🝘
::alch_brick::🝙
::alch_powderedbrick::🝚
::alch_amalgam::🝛
::alch_stratumsuperstratum::🝜
::alch_stratumsuperstratum_alt::🝝
::alch_sublimation::🝞
::alch_precipitate::🝟
::alch_distill::🝠
::alch_dissolve::🝡
::alch_dissolve_alt::🝢
::alch_purify::🝣
::alch_putrefaction::🝤
::alch_crucible::🝥
::alch_crucible_alt::🝦
::alch_crucible_alt2::🝧
::alch_crucible_alt3::🝨
::alch_crucible_alt4::🝩
::alch_alembic::🝪
::alch_bathofmary::🝫
::alch_bathofvapours::🝬
::alch_retort::🝭
::alch_hour::🝮
::alch_night::🝯
::alch_daynight::🝰
::alch_month::🝱
::alch_halfdram::🝲
::alch_halfounce::🝳

